<a href="https://colab.research.google.com/github/Kpranay3151/Python-Basics-Conditional-Loops/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [15]:
#1
np.vander([5,2,3,4],5)

array([[625, 125,  25,   5,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])

In [18]:
def matrix(l,n):
  ans=[]
  for i in l:
    t=[]
    for j in range(n-1,-1,-1):
      t.append(i**j)
    ans.append(t)
  return (np.array(ans))

In [19]:
print(matrix([5,2,3,4],5))

[[625 125  25   5   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]


In [40]:
#2
def movingavg(l,n):
  csum=np.cumsum(l,dtype=float)
  return csum[n-1:]/3

In [41]:
print(movingavg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3))

[  5.           5.66666667   8.33333333  11.66666667  15.33333333
  37.          61.          88.         121.         154.33333333
 204.33333333]
